# Generated by Django 3.2.16 on 2024-10-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241025_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок отображения'),
        ),
    ]
